description: A Risk-Informed Subjective Evaluation and Eye-tracking (RISEE) dataset. <br> Work by Xinzheng Wu, Junyi Chen, Peiyi Wang, Shunxiang Chen, and Yong Shen<br>Tongji University<br> 
theme: jekyll-theme-cayman
links:
  preprint: https://chinaxiv.org/abs/202507.00069?locale=en
  code: https://github.com/IVtest-Lab/RISEE_dataset
  paper: /src/pdfs/RISEE_Preprint_ITSC2025_Accepted.pdf
