description: A Risk-Informed Subjective Evaluation and Eye-tracking (RISEE) dataset. <br> Work by Xinzheng Wu, Junyi Chen, Peiyi Wang, Shunxiang Chen, Haolan Meng, and Yong Shen<br><span style="font-style: italic;">Tongji University</span><br> <span style="color: #555 ;font-weight: bold;">ITSC 2025</span><br> 
theme: jekyll-theme-cayman
links:
  preprint: https://chinaxiv.org/abs/202507.00069?locale=en
  code: https://github.com/IVtest-Lab/RISEE_dataset
  paper: /RISEE_dataset//src/pdfs/RISEE_Preprint_ITSC2025_Accepted.pdf
